---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.4
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checks
        uses: actions/checkout@v4
      - name: Test
        uses: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        uses: docker-compose run --rm app sh -c "flake8"
